source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-seo-tag'
gem'jekyll-assets'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate-v2', '2.0.0'
gem 'jekyll-scholar'
gem 'jekyll-responsive_image'
gem 'jekyll-last-modified-at'
gem 'jekyll_github_sample'
gem 'jekyll-ebook'
